Add doc for TOR102 torch.load without weights_only parameter is unsafe
pytorch-labs/torchfix pull request #60
Opened 2024-06-05 06:53 UTC by swayam0322

Fixed subpart of issue #56 under Docathon-24

2024-06-07 18:53 UTC, kit1980 requested changes
Standalone code blocks (with 3 backtics) look out of place, please make them inline or maybe remove.

2024-06-07 18:53 UTC, kit1980 commented on README.md
> +#### torch.load
There should not be a level 3 and level 4 header, as TOR102 is just one item.
See TOR003 for example.

2024-06-07 18:53 UTC, kit1980 commented on README.md
> +### TOR201 Use of deprecated parameter
There should not be a level 3 and level 4 header, as TOR102 is just one item.
See TOR003 for example.

The title should be specific for the issue, not generic.

2024-06-07 18:53 UTC, kit1980 commented on README.md
> +### TOR202 Use of deprecated function
There should not be a level 3 and level 4 header, as TOR102 is just one item.
See TOR003 for example.

The title should be specific for the issue, not generic.

2024-06-07 21:15 UTC, swayam0322 commented
@kit1980 Made the necessary changes

2024-06-17 19:02 UTC, kit1980 requested changes

2024-06-17 19:02 UTC, kit1980 commented on README.md
> +Explicitly set `weights_only=False` only if you trust the data you load and full pickle functionality is needed,
Only part of the sentence?

2024-06-17 19:03 UTC, kit1980 commented on README.md
>  ## License
Should be an empty line before a header.

2024-06-17 20:01 UTC, swayam0322 commented on README.md
> +Explicitly set `weights_only=False` only if you trust the data you load and full pickle functionality is needed,
Added the remaining text

2024-06-21 00:18 UTC, kit1980 commented on README.md
> +If the input parameter is true, the corresponding backend should be added to the input list of `sdpa_kernel`.
This sentence doesn't make sense to me. "added to the input list of `sdpa_kernel`" - but we are removing `sdp_kernel`.

2024-06-21 00:20 UTC, kit1980 commented on README.md
> +The parameter `pretrained` has been deprecated in TorchVision models since PyTorch version 1.12.0. The `weights` parameter should be used instead.
Doesn't make sense.

2024-06-21 00:21 UTC, kit1980 commented
Sorry, I'm going to close this PR as a lot of things doesn't make sense even on a cursory reading, and correcting this takes more effort than doing from scratch.

2024-06-21 00:21 UTC, closed without merging